joshinary/joshinary/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^words/', include('words.urls', namespace="words")),
    url(r'^admin/', include(admin.site.urls)),
]

joshinary/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^words/', include('words.urls', namespace="words")),
    url(r'^admin/', include(admin.site.urls)),
]

joshinary/words/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	# ex: /words/
	url(r'^$', views.index, name='index'),
	# ex: /words/5/
	url(r'^(?P<word_id>[0-9]+)/$', views.detail, name='detail'),
]

joshinary/words/models.py
import datetime

from django.db import models

from django.utils import timezone

class Word(models.Model):
	id = models.AutoField(primary_key=True)
	word = models.CharField(db_index=True,max_length=255)
	short_definition = models.CharField(max_length=255)
	created_date = models.DateTimeField(auto_now_add=True)
	updated_date = models.DateTimeField(auto_now=True)
	long_definition = models.TextField()

	def __str__(self):
		return self.word

	def was_created_recently(self):
		return self.created_date >= timezone.now() - datetime.timedelta(days=1)

	def was_updated_recently(self):
		return self.updated_date >= timezone.now() - datetime.timedelta(days=1)

joshinary/words/views.py
from django.shortcuts import render

from .models import Word

def index(request):
	latest_word_list = Word.objects.order_by('-created_date')[:5]
	context = {'latest_word_list': latest_word_list}
	return render(request, 'words/index.html', context)

def detail(request, word_id):
	try:
		word = Word.objects.get(pk=word_id)
	except Word.DoesNotExist:
		raise Http404("Word does not exist")
	return render(request, 'words/detail.html', {'word': word})

joshinary/words/templates/words/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Joshinary Home</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
		<meta name="author" content="ADD AUTHOR INFORMATION">
		<meta name="robots" content="index, follow">

		<!-- Bootstrap Core CSS file -->
		<link rel="stylesheet" href="../static/assets/css/bootstrap.min.css">
		<!-- Override CSS file - add your own CSS rules -->
		  <link href="../static/assets/css/styles.css" rel="stylesheet" type="text/css" />


	</head>
	<body>
		<!-- Navigation -->
	    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
			<div class="container-fluid">

				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" style="padding-left:50px"href="/words"><img src="../static/assets/img/JoshinaryLogo.png" height="20px"></a>
					<ul class="nav navbar-nav">
					<li class="navBarWords"><a href="#">Browse</a></li>
					<li class="navBarWords" style="padding-right:10px;"><a href="/words">Home</a></li>
				</ul>
					<div class="">
						<form action="#">
							<div class="input-group" style="padding-top:8.5px;">
								<input type="text" class="form-control" placeholder="Search" id="search-form">
								<span class="input-group-btn">
										<button class="btn btn-default" type="button">
											<span class="glyphicon glyphicon-search"></span>
											<span class="sr-only">Search</span>
										</button>
								</span>
							</div>
						</form>
					</div>
				</div>
				<!-- /.navbar-header -->
				<!-- /.navbar-collapse -->
			</div>
			<!-- /.container-fluid -->
		</nav>
		<!-- /.navbar -->

		<!-- Page Content -->
		<div class="container-fluid">
			<div style="text-align:center;">
			  <ul class="pagination">
			    <li><a href="#">A</a></li>
			    <li><a href="#">B</a></li>
			    <li><a href="#">C</a></li>
			    <li><a href="#">D</a></li>
			    <li><a href="#">E</a></li>
					<li><a href="#">F</a></li>
			    <li><a href="#">G</a></li>
			    <li><a href="#">H</a></li>
			    <li><a href="#">I</a></li>
					<li><a href="#">J</a></li>
					<li><a href="#">K</a></li>
					<li><a href="#">L</a></li>
					<li><a href="#">M</a></li>
					<li><a href="#">N</a></li>
					<li><a href="#">O</a></li>
					<li><a href="#">P</a></li>
					<li><a href="#">Q</a></li>
					<li><a href="#">R</a></li>
					<li><a href="#">S</a></li>
					<li><a href="#">T</a></li>
					<li><a href="#">U</a></li>
					<li><a href="#">V</a></li>
					<li><a href="#">W</a></li>
					<li><a href="#">X</a></li>
					<li><a href="#">Y</a></li>
			    <li><a href="#">Z</a></li>
			  </ul>
			</div>
			<!-- /.row -->

			<div class="row">
				<div class="col-sm-8">
								<!-- Words -->
								<div class="well">

									<div class="media">
										<div class="media-body">
											<h4 class="margin-t-0"><a href="{% url 'words:detail' word.id %}">{{ word.word }}</a></h4>
			<!--FontWord and fontWordBody in style.css-->
											<p class="fontWord" >{{ word.short_definition }}</p>
											<p class="fontWordBody">{{ word.long_definition }}</p>
											<p>
												<button class="btn btn-sm btn-default">
													<span class="glyphicon glyphicon-thumbs-up"></span> Upvote
												</button>
												<button class="btn btn-sm btn-default">
													<span class="glyphicon glyphicon-thumbs-down"></span> Downvote
												</button>
												<button class="btn btn-sm btn-default">
													<span class="glyphicon glyphicon-comment"></span> Reply
												</button>
											</p>
										</div>
									</div>
								</div>

					<!-- Pager -->
					<nav>
						<ul class="pager">
							<li class="previous"><a href="#"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Older</a></li>
							<li class="next"><a href="">Newer <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></a></li>
						</ul>
					</nav>
				</div>
				<div class="col-sm-4" style="Padding-top: 20px;">
					<!-- list group -->
					<div class="list-group margin-b-3">
					    <a href="#" class="active list-group-item">Top</a>
					    <a href="#" class="list-group-item">New</a>
					    <a href="#" class="list-group-item">Favorites</a>
					</div>
                	<!-- Panel -->
					<div class="panel panel-default">
						<div class="panel-heading">
							<h4 class="panel-title">Sidebar panel widget</h4>
						</div>
						<div class="panel-body">
							<p>This is a bunch of words</p>
						</div>
					</div>
				</div>
			</div>
			<!-- /.row -->
			<hr>
			<footer class="margin-tb-3">
				<div class="row">
					<div class="col-lg-12">
						<p>Copyright &copy; Nitser 2016</p>
					</div>
				</div>
			</footer>
		</div>
		<!-- /.container-fluid -->

		<!-- JQuery scripts -->
	    <script src="static/assets/js/jquery-1.11.2.min.js"></script>

		<!-- Bootstrap Core scripts -->
		<script src="static/assets/js/bootstrap.min.js"></script>
  </body>
</html>

joshinary/words/templates/words/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Joshinary Home</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
		<meta name="author" content="ADD AUTHOR INFORMATION">
		<meta name="robots" content="index, follow">

		<!-- Bootstrap Core CSS file -->
		<link rel="stylesheet" href="static/assets/css/bootstrap.min.css">
		<!-- Override CSS file - add your own CSS rules -->
		  <link href="static/assets/css/styles.css" rel="stylesheet" type="text/css" />

	</head>
	<body>
		<!-- Navigation -->
	    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
			<div class="container-fluid">

				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" style="padding-left:50px"href="/words"><img src="static/assets/img/JoshinaryLogo.png" height="20px"></a>
					<ul class="nav navbar-nav">
					<li class="navBarWords"><a href="#">Browse</a></li>
					<li class="navBarWords" style="padding-right:10px;"><a href="/words">Home</a></li>
				</ul>
					<div class="">
						<form action="#">
							<div class="input-group" style="padding-top:8.5px;">
								<input type="text" class="form-control" placeholder="Search" id="search-form">
								<span class="input-group-btn">
										<button class="btn btn-default" type="button">
											<span class="glyphicon glyphicon-search"></span>
											<span class="sr-only">Search</span>
										</button>
								</span>
							</div>
						</form>
					</div>
				</div>
				<!-- /.navbar-header -->
				<!-- /.navbar-collapse -->
			</div>
			<!-- /.container-fluid -->
		</nav>
		<!-- /.navbar -->

		<!-- Page Content -->
		<div class="container-fluid">
			<div style="text-align:center;">
			  <ul class="pagination">
			    <li><a href="#">A</a></li>
			    <li><a href="#">B</a></li>
			    <li><a href="#">C</a></li>
			    <li><a href="#">D</a></li>
			    <li><a href="#">E</a></li>
					<li><a href="#">F</a></li>
			    <li><a href="#">G</a></li>
			    <li><a href="#">H</a></li>
			    <li><a href="#">I</a></li>
					<li><a href="#">J</a></li>
					<li><a href="#">K</a></li>
					<li><a href="#">L</a></li>
					<li><a href="#">M</a></li>
					<li><a href="#">N</a></li>
					<li><a href="#">O</a></li>
					<li><a href="#">P</a></li>
					<li><a href="#">Q</a></li>
					<li><a href="#">R</a></li>
					<li><a href="#">S</a></li>
					<li><a href="#">T</a></li>
					<li><a href="#">U</a></li>
					<li><a href="#">V</a></li>
					<li><a href="#">W</a></li>
					<li><a href="#">X</a></li>
					<li><a href="#">Y</a></li>
			    <li><a href="#">Z</a></li>
			  </ul>
			</div>
			<!-- /.row -->

			<div class="row">
				<div class="col-sm-8">
					<h2>
						{% if latest_word_list %}
						<ul>
						{% for word in latest_word_list %}
								<!-- Words -->
						<div class="well">
							<div class="media">
								<div class="media-body">
									<h4 class="margin-t-0"><a href="{% url 'words:detail' word.id %}">{{ word.word }}</a></h4>
									<!--FontWord and fontWordBody in style.css-->
									<p class="fontWord" >{{ word.short_definition }}</p>
									<p class="fontWordBody">{{ word.long_definition }}</p>
									<p>
										<button class="btn btn-sm btn-default">
											<span class="glyphicon glyphicon-thumbs-up"></span> Upvote
										</button>
										<button class="btn btn-sm btn-default">
											<span class="glyphicon glyphicon-thumbs-down"></span> Downvote
										</button>
										<button class="btn btn-sm btn-default">
											<span class="glyphicon glyphicon-comment"></span> Reply
										</button>
									</p>
								</div>
							</div>
						</div>
					{% endfor %}
					</ul>
					{% else %}
							<p>No words are available.</p>
					{% endif %}
	  		</h2>
					<!-- Pager -->
					<nav>
						<ul class="pager">
							<li class="previous"><a href="#"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Older</a></li>
							<li class="next"><a href="">Newer <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></a></li>
						</ul>
					</nav>
				</div>
				<div class="col-sm-4" style="Padding-top: 20px;">
					<!-- list group -->
					<div class="list-group margin-b-3">
					    <a href="#" class="active list-group-item">Top</a>
					    <a href="#" class="list-group-item">New</a>
					    <a href="#" class="list-group-item">Favorites</a>
					</div>
                	<!-- Panel -->
					<div class="panel panel-default">
						<div class="panel-heading">
							<h4 class="panel-title">Sidebar panel widget</h4>
						</div>
						<div class="panel-body">
							<p>This is a bunch of words</p>
						</div>
					</div>
				</div>
			</div>
			<!-- /.row -->
			<hr>
			<footer class="margin-tb-3">
				<div class="row">
					<div class="col-lg-12">
						<p>Copyright &copy; Nitser 2016</p>
					</div>
				</div>
			</footer>
		</div>
		<!-- /.container-fluid -->

		<!-- JQuery scripts -->
	    <script src="static/assets/js/jquery-1.11.2.min.js"></script>

		<!-- Bootstrap Core scripts -->
		<script src="static/assets/js/bootstrap.min.js"></script>
  </body>
</html>